### ISSUE TITLE
Test suite should be made compatible with final specification for API Features

### ISSUE THREAD

**Issue by sampov2** [opengeospatial/ets-ogcapi-features-1.0#78] opened 2019-10-31 08:20 UTC
The test suites should be reviewed and corrected to be in line with the final version of the specification (http://docs.opengeospatial.org/is/17-069r3/17-069r3.html). For example collections now have an "id" instead of "name" and most if not all the test code seems to still be using the old field name.

One example:
https://github.com/opengeospatial/ets-wfs30/blob/d4e9250e4adab69feb3db11df37cd385c55c43d1/src/main/java/org/opengis/cite/wfs30/collections/FeatureCollectionsMetadataOperation.java#L220

**Comment by dstenger** [comment] 2019-11-04 16:17
Thank you for reporting.

We are already reviewing the test suite and document the results in https://github.com/opengeospatial/ets-ogcapi-features-1.0/issues/45.
Any help is welcome.

**Comment by lgoltz** [comment] 2019-11-11 06:00
Duplicate of #45

**Closed** 2019-11-11 06:01 UTC
Labels: duplicate
